---

classes:
  CANdleConfigUtil:
    methods:
      StripTypeDifferent:
      BrightnessScalarDifferent:
      DisableWhenLOSDifferent:
      StatusLedOffWhenActiveDifferent:
      VBatOutputModeDifferent:
